### ISSUE TITLE
[BUG] API Documentation should include Rust API and put it before AssemblyScript API

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/docs#180] opened 2020-01-28 17:05 UTC
Currently https://docs.nearprotocol.com/docs/api/quickstart page does not have Rust API, it only has AssemblyScript API. We need to add Rust API and put it before AssemblyScript API, since Rust is our primary language for smart contracts. CC @janedegtiareva

**Comment by amgando** [comment] 2020-02-05 09:28
if the problem is with Rust being absent from left-hand-side navigation then this has more to do with limitations of our documentation system than anything else.

currently Rust for contracts is well documented by  the `near-bindgen` repo README which is linked on this page.  i can change the order to promote Rust first. would that be sufficient?

**Comment by amgando** [comment] 2020-03-03 09:56
closing since we've promoted Rust above AssemblyScript throughout

see screenshot below from https://docs.nearprotocol.com/docs/api/quickstart

![image](https://user-images.githubusercontent.com/24913/75764042-54d07000-5d4e-11ea-83c1-8e7d7d2b08b6.png)

**Closed by amgando** 2020-03-03 09:56 UTC
Labels: bug
